### PR TITLE
Support for o200k_base and gpt-4o (omni) model

### PR DESCRIPTION
**Pull request by winzig**
Notes: 

- I added in the new test plans for o200k based on output from tiktoken
- I added a SetupO200k() in CompareBenchmark (and renamed Setup to SetupCL200k), but it's not flagged as the GlobalSetup, so not currently used/benchmarked. Wasn't sure if you wanted to re-benchmark with the new encoding?

### CODE REVIEW

**Comment by winzig** [comment]
Fixed some issues that I found, all tests now passing.

**Comment by dmitry-brazhenko** [comment]
Thank you so much for contribution!

**Comment by dmitry-brazhenko** [comment]
I added minor fixes around failed tests in macos pipeline and will merge it here: https://github.com/dmitry-brazhenko/SharpToken/pull/43

**Comment by dmitry-brazhenko** [comment]
Did it here: https://github.com/dmitry-brazhenko/SharpToken/pull/43

**Pull request closed without merging**
